#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3

# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
echo "Wrong user"
exit 1
fi
sudo yunohost app setting jeedom admin_user -v $user

sudo yunohost app checkurl $domain$path -a jeedom
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Packages needed
sudo apt-get install -y ffmpeg libssh2-php ntp unzip php5-cli php5-curl php5-json nodejs usb-modeswitch python-serial

# Copy of sources files
final_path=/var/www/jeedom
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo mkdir $final_path/tmp
sudo chmod 775 -R $final_path
sudo chown -R www-data:www-data $final_path

# For nginx user to be able to communicate with domotic devices
sudo adduser www-data dialout
sudo adduser www-data gpio

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')
# Use 'jeedom' as database name and user
db_user=jeedom

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting jeedom mysqlpwd -v $db_pwd

# Configure Jeedom database and initialize app
sudo cp $final_path/core/config/common.config.sample.php $final_path/core/config/common.config.php
sudo sed -i -e "s/#PASSWORD#/${db_pwd}/g" $final_path/core/config/common.config.php 
sudo chown www-data:www-data $final_path/core/config/common.config.php
sudo php $final_path/install/install.php mode=force

# Configure Nginx and reload
sudo sed -i "s@PATHTOCHANGE@$path@g"  ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/jeedom.conf
sudo service nginx reload

# Configure and start the NodeJS service for Jeedom
sudo cp $final_path/jeedom /etc/init.d/
sudo chmod +x /etc/init.d/jeedom
sudo update-rc.d jeedom defaults
sudo sed -i 's%PATH_TO_JEEDOM="/usr/share/nginx/www/jeedom"%PATH_TO_JEEDOM="/var/www/jeedom"%g' /etc/init.d/jeedom
sudo service jeedom start

# Configure LDAP and the Admin User
mysql -u $db_user -p$db_pwd $db_user < ../conf/ldap_config.sql
mysql -u $db_user -p$db_pwd $db_user -e "INSERT INTO user (id, login, password, options, hash, rights) VALUES ('0', '$user', '', NULL, NULL, '{\"admin\":1}');"

# Access to API without SSO
sudo yunohost app setting jeedom unprotected_uris -v "/core/api/jeeApi.php"
sudo yunohost app ssowatconf
