#!/bin/bash

db_user=jeedom
db_name=jeedom
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting owncloud domain)
mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

sudo rm /etc/nginx/conf.d/$domain.d/jeedom.conf
sudo rm -rf /var/www/jeedom

sudo service nginx reload
sudo yunohost app ssowatconf 

sudo service jeedom stop
sudo update-rc.d jeedom remove
sudo rm /etc/init.d/jeedom
